name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        docker build ./api/ -t ${{ secrets.Aungpaolol }}/app1-api:latest
        docker build ./front/ -t ${{ secrets.Aungpaolol }}/app1-frontend:latest

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.aungpaolol32 }}" | docker login -u ${{ secrets.Aungpaolol }} --password-stdin

    - name: Push images to Docker Hub
      run: |
        docker push ${{ secrets.Aungpaolol }}/app1-api:latest
        docker push ${{ secrets.Aungpaolol }}/app1-frontend:latest